### ISSUE TITLE
License badge link is broken

### ISSUE THREAD

**Issue by ReubenFrankel** [DanielPDWalker/tap-theme-parks#37]
The license badge links to `https://github.com/DanielPDWalker/tap-theme-parks/master/LICENSE`, which returns a 404 message.

This works:

```
[![GitHub License](https://img.shields.io/github/license/DanielPDWalker/tap-theme-parks)](https://github.com/DanielPDWalker/tap-theme-parks/blob/main/LICENSE)
```

[![GitHub License](https://img.shields.io/github/license/DanielPDWalker/tap-theme-parks)](https://github.com/DanielPDWalker/tap-theme-parks/blob/main/LICENSE)

**Comment by ReubenFrankel** [comment]
:rat:

**Comment by DanielPDWalker** [comment]
Fixed.
